
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - /c/Users/rafae/Documents/ProjetDockerKubernetes/kubernetesApp/app/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  backend:
    build:
      context: "C:/Users/rafae/OneDrive/Documents/Ingénieur/I1/MicroService/ProjetDockerKubernetes/kubernetesWeb/server"
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: myappdb
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - mynetwork

  frontend:
    build:
      context: "C:/Users/rafae/OneDrive/Documents/Ingénieur/I1/MicroService/ProjetDockerKubernetes/kubernetesWeb/client"
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
      - backend
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
